os:
  - linux
  - osx
  - windows

dist: xenial
osx_image: xcode9.3
language: c

addons:
  apt:
    packages:
      - openjdk-8-jdk
      - rpm
      - wine
      - fakeroot

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then xvfb-run -a ./gradlew test all; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./gradlew current; fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      choco install jdk8
      JAVA_HOME='c:/Program Files/Java/jdk1.8.0_191' ./gradlew --info test win-installer
    fi
