os:
  - linux
  - osx
  - windows

dist: xenial
language: c

addons:
  apt:
    packages:
      - rpm
      - wine
      - fakeroot

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install jdk8; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then xvfb-run -a ./gradlew test all; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./gradlew current; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export JAVA_HOME='/c/Program Files/Java/jdk1.8.0'*; ./gradlew current; fi
