os:
  - linux
  - osx

dist: xenial
language: java

addons:
  apt:
    packages:
      - rpm
      - wine
      - fakeroot

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then xvfb-run -a ./gradlew test all; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./gradlew current; fi
